[package]
name = 'rjellyfishr'
version = '0.1.0'
edition = '2021'

[lib]
crate-type = [ 'staticlib' ]
name = 'rjellyfishr'

[dependencies]
ahash = "0.8.11"
extendr-api = '*'
rayon = "1.10.0"
smallvec = "1.13.2"
unicode-normalization = "0.1.24"
unicode-segmentation = "1.12.0"
