# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_jellyfishr_wrappers", use_symbols = TRUE, package_name = "jellyfishr")

#' @usage NULL
#' @useDynLib jellyfishr, .registration = TRUE
NULL

#' @export
damerau_levenshtein_distance <- function(s1, s2) .Call(wrap__damerau_levenshtein_distance, s1, s2)

#' @export
hamming_distance <- function(s1, s2) .Call(wrap__hamming_distance, s1, s2)

#' @export
jaro_similarity <- function(s1, s2) .Call(wrap__jaro_similarity, s1, s2)

#' @export
jaro_winkler_similarity <- function(s1, s2) .Call(wrap__jaro_winkler_similarity, s1, s2)

#' @export
levenshtein_distance <- function(s1, s2) .Call(wrap__levenshtein_distance, s1, s2)


# nolint end
