# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_jellyfishr_wrappers", use_symbols = TRUE, package_name = "jellyfishr")

#' @usage NULL
#' @useDynLib jellyfishr, .registration = TRUE
NULL

#' @export
damerau_levenshtein_distance <- function(s1, s2) .Call(wrap__damerau_levenshtein_distance, s1, s2)

#' @export
hamming_distance <- function(s1, s2) .Call(wrap__hamming_distance, s1, s2)

#' @export
jaccard_distance <- function(s1, s2, ngram_size) .Call(wrap__jaccard_distance, s1, s2, ngram_size)

#' @export
jaro_distance <- function(s1, s2) .Call(wrap__jaro_distance, s1, s2)

#' @export
jaro_winkler_distance <- function(s1, s2) .Call(wrap__jaro_winkler_distance, s1, s2)

#' @export
levenshtein_distance <- function(s1, s2) .Call(wrap__levenshtein_distance, s1, s2)

#' @export
metaphone <- function(s) .Call(wrap__metaphone, s)

#' @export
nysiis <- function(s) .Call(wrap__nysiis, s)

#' @export
soundex <- function(s) .Call(wrap__soundex, s)


# nolint end
